import { Food } from './models';

const MOCK_SEARCH_TIMESTAMP = '2026-01-01T00:00:00.000Z';

export const mockFoodSearchFoods: Food[] = [
  {
    id: 'search-food-banana',
    source: 'mock-food-search',
    sourceFoodId: 'mock-search-banana',
    name: '바나나',
    brandName: null,
    category: '과일',
    servingSize: 100,
    servingUnit: 'g',
    nutritionPerServing: {
      caloriesKcal: 89,
      carbohydrateG: 22.8,
      proteinG: 1.1,
      fatG: 0.3,
      sugarsG: 12.2,
      sodiumMg: 1,
      fiberG: 2.6,
      saturatedFatG: 0.1,
      transFatG: 0,
      cholesterolMg: 0,
    },
    updatedAt: MOCK_SEARCH_TIMESTAMP,
  },
  {
    id: 'search-food-apple',
    source: 'mock-food-search',
    sourceFoodId: 'mock-search-apple',
    name: '사과',
    brandName: null,
    category: '과일',
    servingSize: 150,
    servingUnit: 'g',
    nutritionPerServing: {
      caloriesKcal: 78,
      carbohydrateG: 20.9,
      proteinG: 0.4,
      fatG: 0.3,
      sugarsG: 15.6,
      sodiumMg: 2,
      fiberG: 3.6,
      saturatedFatG: 0.1,
      transFatG: 0,
      cholesterolMg: 0,
    },
    updatedAt: MOCK_SEARCH_TIMESTAMP,
  },
  {
    id: 'search-food-boiled-egg',
    source: 'mock-food-search',
    sourceFoodId: 'mock-search-boiled-egg',
    name: '삶은 달걀',
    brandName: null,
    category: '난류',
    servingSize: 1,
    servingUnit: '개',
    nutritionPerServing: {
      caloriesKcal: 78,
      carbohydrateG: 0.6,
      proteinG: 6.3,
      fatG: 5.3,
      sugarsG: 0.6,
      sodiumMg: 62,
      fiberG: 0,
      saturatedFatG: 1.6,
      transFatG: 0,
      cholesterolMg: 186,
    },
    updatedAt: MOCK_SEARCH_TIMESTAMP,
  },
  {
    id: 'search-food-kimchi-stew',
    source: 'mock-food-search',
    sourceFoodId: 'mock-search-kimchi-stew',
    name: '김치찌개',
    brandName: null,
    category: '국/찌개',
    servingSize: 350,
    servingUnit: 'g',
    nutritionPerServing: {
      caloriesKcal: 210,
      carbohydrateG: 14,
      proteinG: 15,
      fatG: 10,
      sugarsG: 5,
      sodiumMg: 980,
      fiberG: 3,
      saturatedFatG: 2.8,
      transFatG: null,
      cholesterolMg: 35,
    },
    updatedAt: MOCK_SEARCH_TIMESTAMP,
  },
  {
    id: 'search-food-tofu',
    source: 'mock-food-search',
    sourceFoodId: 'mock-search-tofu',
    name: '두부',
    brandName: null,
    category: '콩류',
    servingSize: 100,
    servingUnit: 'g',
    nutritionPerServing: {
      caloriesKcal: 84,
      carbohydrateG: 2.8,
      proteinG: 8.1,
      fatG: 4.8,
      sugarsG: 0.7,
      sodiumMg: 7,
      fiberG: 0.3,
      saturatedFatG: 0.7,
      transFatG: 0,
      cholesterolMg: 0,
    },
    updatedAt: MOCK_SEARCH_TIMESTAMP,
  },
  {
    id: 'search-food-ramen',
    source: 'mock-food-search',
    sourceFoodId: 'mock-search-ramen',
    name: '라면',
    brandName: '목데이터',
    category: '면류',
    servingSize: 120,
    servingUnit: 'g',
    nutritionPerServing: {
      caloriesKcal: 500,
      carbohydrateG: 79,
      proteinG: 10,
      fatG: 16,
      sugarsG: null,
      sodiumMg: 1790,
      fiberG: null,
      saturatedFatG: 8,
      transFatG: 0,
      cholesterolMg: 0,
    },
    updatedAt: MOCK_SEARCH_TIMESTAMP,
  },
  {
    id: 'search-food-sweet-potato',
    source: 'mock-food-search',
    sourceFoodId: 'mock-search-sweet-potato',
    name: '고구마',
    brandName: null,
    category: '구황작물',
    servingSize: 130,
    servingUnit: 'g',
    nutritionPerServing: {
      caloriesKcal: 112,
      carbohydrateG: 26.1,
      proteinG: 2,
      fatG: 0.1,
      sugarsG: 5.4,
      sodiumMg: 46,
      fiberG: 3.9,
      saturatedFatG: 0,
      transFatG: 0,
      cholesterolMg: 0,
    },
    updatedAt: MOCK_SEARCH_TIMESTAMP,
  },
  {
    id: 'search-food-tuna-can',
    source: 'mock-food-search',
    sourceFoodId: 'mock-search-tuna-can',
    name: '참치캔',
    brandName: '목데이터',
    category: '가공식품',
    servingSize: 100,
    servingUnit: 'g',
    nutritionPerServing: {
      caloriesKcal: 190,
      carbohydrateG: null,
      proteinG: 24,
      fatG: 10,
      sugarsG: null,
      sodiumMg: 350,
      fiberG: null,
      saturatedFatG: 1.6,
      transFatG: null,
      cholesterolMg: 40,
    },
    updatedAt: MOCK_SEARCH_TIMESTAMP,
  },
];
