import { Food, Meal } from './models';

const MOCK_TIMESTAMP = '2026-01-01T00:00:00.000Z';

export type TodayMockData = {
  foods: Food[];
  meals: Meal[];
};

export function createMockTodayData(date: string): TodayMockData {
  const foods: Food[] = [
    {
      id: 'food-oatmeal',
      source: 'mock',
      sourceFoodId: 'mock-oatmeal',
      name: '오트밀',
      brandName: null,
      category: '곡류',
      servingSize: 80,
      servingUnit: 'g',
      nutritionPerServing: {
        caloriesKcal: 300,
        carbohydrateG: 51,
        proteinG: 10.4,
        fatG: 5.6,
        sugarsG: 1.1,
        sodiumMg: 4,
        fiberG: 8,
        saturatedFatG: 1,
        transFatG: 0,
        cholesterolMg: 0,
      },
      updatedAt: MOCK_TIMESTAMP,
    },
    {
      id: 'food-greek-yogurt',
      source: 'mock',
      sourceFoodId: 'mock-greek-yogurt',
      name: '그릭요거트',
      brandName: '목데이터',
      category: '유제품',
      servingSize: 150,
      servingUnit: 'g',
      nutritionPerServing: {
        caloriesKcal: 120,
        carbohydrateG: 8,
        proteinG: 15,
        fatG: null,
        sugarsG: 5,
        sodiumMg: 55,
        fiberG: null,
        saturatedFatG: null,
        transFatG: null,
        cholesterolMg: 10,
      },
      updatedAt: MOCK_TIMESTAMP,
    },
    {
      id: 'food-brown-rice',
      source: 'mock',
      sourceFoodId: 'mock-brown-rice',
      name: '현미밥',
      brandName: null,
      category: '밥류',
      servingSize: 210,
      servingUnit: 'g',
      nutritionPerServing: {
        caloriesKcal: 320,
        carbohydrateG: 69,
        proteinG: 6.5,
        fatG: 1.8,
        sugarsG: 0.3,
        sodiumMg: 5,
        fiberG: 3.2,
        saturatedFatG: 0.4,
        transFatG: 0,
        cholesterolMg: 0,
      },
      updatedAt: MOCK_TIMESTAMP,
    },
    {
      id: 'food-chicken-breast',
      source: 'mock',
      sourceFoodId: 'mock-chicken-breast',
      name: '닭가슴살',
      brandName: null,
      category: '육류',
      servingSize: 100,
      servingUnit: 'g',
      nutritionPerServing: {
        caloriesKcal: 165,
        carbohydrateG: 0,
        proteinG: 31,
        fatG: 3.6,
        sugarsG: 0,
        sodiumMg: 74,
        fiberG: 0,
        saturatedFatG: 1,
        transFatG: 0,
        cholesterolMg: 85,
      },
      updatedAt: MOCK_TIMESTAMP,
    },
    {
      id: 'food-salmon',
      source: 'mock',
      sourceFoodId: 'mock-salmon',
      name: '연어구이',
      brandName: null,
      category: '어패류',
      servingSize: 120,
      servingUnit: 'g',
      nutritionPerServing: {
        caloriesKcal: 250,
        carbohydrateG: null,
        proteinG: 25,
        fatG: 15,
        sugarsG: null,
        sodiumMg: 60,
        fiberG: null,
        saturatedFatG: 3.1,
        transFatG: 0,
        cholesterolMg: 70,
      },
      updatedAt: MOCK_TIMESTAMP,
    },
    {
      id: 'food-salad',
      source: 'mock',
      sourceFoodId: 'mock-salad',
      name: '채소 샐러드',
      brandName: null,
      category: '채소류',
      servingSize: 180,
      servingUnit: 'g',
      nutritionPerServing: {
        caloriesKcal: 95,
        carbohydrateG: 14,
        proteinG: 3,
        fatG: 3.5,
        sugarsG: 6,
        sodiumMg: null,
        fiberG: 5.5,
        saturatedFatG: 0.5,
        transFatG: 0,
        cholesterolMg: 0,
      },
      updatedAt: MOCK_TIMESTAMP,
    },
  ];

  const meals: Meal[] = [
    {
      id: 'meal-breakfast',
      date,
      type: 'breakfast',
      foods: [
        {
          id: 'meal-food-oatmeal',
          foodId: 'food-oatmeal',
          mealId: 'meal-breakfast',
          quantity: 1,
          amount: 80,
          amountUnit: 'g',
          checked: true,
          calculatedNutrition: foods[0].nutritionPerServing,
          createdAt: MOCK_TIMESTAMP,
          updatedAt: MOCK_TIMESTAMP,
        },
        {
          id: 'meal-food-greek-yogurt',
          foodId: 'food-greek-yogurt',
          mealId: 'meal-breakfast',
          quantity: 1,
          amount: 150,
          amountUnit: 'g',
          checked: true,
          calculatedNutrition: foods[1].nutritionPerServing,
          createdAt: MOCK_TIMESTAMP,
          updatedAt: MOCK_TIMESTAMP,
        },
      ],
      createdAt: MOCK_TIMESTAMP,
      updatedAt: MOCK_TIMESTAMP,
    },
    {
      id: 'meal-lunch',
      date,
      type: 'lunch',
      foods: [
        {
          id: 'meal-food-brown-rice',
          foodId: 'food-brown-rice',
          mealId: 'meal-lunch',
          quantity: 1,
          amount: 210,
          amountUnit: 'g',
          checked: true,
          calculatedNutrition: foods[2].nutritionPerServing,
          createdAt: MOCK_TIMESTAMP,
          updatedAt: MOCK_TIMESTAMP,
        },
        {
          id: 'meal-food-chicken-breast',
          foodId: 'food-chicken-breast',
          mealId: 'meal-lunch',
          quantity: 1,
          amount: 100,
          amountUnit: 'g',
          checked: false,
          calculatedNutrition: foods[3].nutritionPerServing,
          createdAt: MOCK_TIMESTAMP,
          updatedAt: MOCK_TIMESTAMP,
        },
      ],
      createdAt: MOCK_TIMESTAMP,
      updatedAt: MOCK_TIMESTAMP,
    },
    {
      id: 'meal-dinner',
      date,
      type: 'dinner',
      foods: [
        {
          id: 'meal-food-salmon',
          foodId: 'food-salmon',
          mealId: 'meal-dinner',
          quantity: 1,
          amount: 120,
          amountUnit: 'g',
          checked: false,
          calculatedNutrition: foods[4].nutritionPerServing,
          createdAt: MOCK_TIMESTAMP,
          updatedAt: MOCK_TIMESTAMP,
        },
        {
          id: 'meal-food-salad',
          foodId: 'food-salad',
          mealId: 'meal-dinner',
          quantity: 1,
          amount: 180,
          amountUnit: 'g',
          checked: false,
          calculatedNutrition: foods[5].nutritionPerServing,
          createdAt: MOCK_TIMESTAMP,
          updatedAt: MOCK_TIMESTAMP,
        },
      ],
      createdAt: MOCK_TIMESTAMP,
      updatedAt: MOCK_TIMESTAMP,
    },
  ];

  return { foods, meals };
}
