import { StyleSheet } from 'react-native';

import { colors, fontSize, radius, spacing } from './constants';

const cardShadow = {
  shadowColor: '#1b2819',
  shadowOffset: { height: 4, width: 0 },
  shadowOpacity: 0.08,
  shadowRadius: 12,
  elevation: 2,
};

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.background,
  },
  appContent: {
    flex: 1,
  },
  loadingScreen: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: spacing.xxl,
  },
  loadingTitle: {
    color: colors.text,
    fontSize: fontSize.xl,
    fontWeight: '900',
    letterSpacing: 0,
    textAlign: 'center',
  },
  loadingText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: 19,
    marginTop: spacing.xs,
    textAlign: 'center',
  },
  content: {
    alignSelf: 'center',
    maxWidth: 760,
    paddingBottom: 96,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    width: '100%',
  },
  tabBar: {
    backgroundColor: colors.surface,
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  tabButton: {
    alignItems: 'center',
    borderRadius: radius.md,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: spacing.md,
  },
  tabButtonActive: {
    backgroundColor: colors.primary,
  },
  tabButtonPressed: {
    opacity: 0.72,
  },
  tabButtonText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    fontWeight: '800',
  },
  tabButtonTextActive: {
    color: colors.surface,
  },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.card,
    borderWidth: 1,
    padding: spacing.lg,
    ...cardShadow,
  },
  cardMuted: {
    backgroundColor: colors.surfaceMuted,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  primaryButtonText: {
    color: colors.surface,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  secondaryButtonText: {
    color: colors.primary,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  buttonPressed: {
    opacity: 0.72,
  },
  buttonDisabled: {
    backgroundColor: '#d8ded5',
    borderColor: '#d8ded5',
  },
  buttonDisabledText: {
    color: colors.textMuted,
  },
  selectButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 78,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  selectButtonWithDescription: {
    alignItems: 'flex-start',
    minHeight: 62,
    padding: spacing.md,
  },
  selectButtonActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  selectButtonText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  selectButtonTextActive: {
    color: colors.primary,
  },
  selectButtonDescription: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 17,
    marginTop: spacing.xxs,
  },
  selectButtonDescriptionActive: {
    color: colors.primary,
  },
  noticeBox: {
    backgroundColor: colors.infoSoft,
    borderColor: '#c9dde5',
    borderRadius: radius.md,
    borderWidth: 1,
    marginTop: spacing.md,
    padding: spacing.md,
  },
  noticeBoxWarning: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warningBorder,
  },
  noticeBoxDanger: {
    backgroundColor: colors.dangerSoft,
    borderColor: colors.dangerBorder,
  },
  noticeTitle: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  noticeText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: 19,
    marginTop: spacing.xxs,
  },
  statRow: {
    alignItems: 'center',
    borderBottomColor: '#e8eee4',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
    paddingVertical: spacing.sm,
  },
  statRowLabel: {
    color: colors.textMuted,
    flex: 1,
    fontSize: fontSize.md,
    fontWeight: '700',
  },
  statRowValue: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
    textAlign: 'right',
  },
  header: {
    gap: spacing.xs,
    marginBottom: spacing.md,
  },
  eyebrow: {
    color: colors.primary,
    fontSize: fontSize.md,
    fontWeight: '800',
  },
  title: {
    color: colors.text,
    fontSize: fontSize.display,
    fontWeight: '900',
    letterSpacing: 0,
  },
  dateText: {
    color: colors.textMuted,
    fontSize: fontSize.base,
    lineHeight: 21,
  },
  todayTopStack: {
    gap: spacing.md,
  },
  dateCardHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  dateValueText: {
    color: colors.text,
    fontSize: fontSize.xxl,
    fontWeight: '900',
    letterSpacing: 0,
    marginTop: spacing.xxs,
  },
  dateBadge: {
    backgroundColor: colors.primarySoft,
    borderRadius: radius.pill,
    color: colors.primary,
    fontSize: fontSize.sm,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  dateControlRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.lg,
  },
  dateControlButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: spacing.md,
  },
  dateControlButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  dateControlButtonPressed: {
    opacity: 0.72,
  },
  dateControlButtonText: {
    color: colors.primary,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  dateControlButtonTextActive: {
    color: colors.surface,
  },
  summaryPanel: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.card,
    borderWidth: 1,
    marginTop: spacing.md,
    padding: spacing.lg,
    ...cardShadow,
  },
  summaryPanelHero: {
    padding: spacing.xl,
  },
  summaryHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  evaluationPanel: {
    backgroundColor: colors.surface,
    borderColor: '#d5e4e8',
    borderRadius: radius.card,
    borderWidth: 1,
    marginTop: spacing.md,
    padding: spacing.lg,
    ...cardShadow,
  },
  evaluationHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  evaluationStatusBadge: {
    backgroundColor: colors.secondarySoft,
    borderRadius: radius.pill,
    color: colors.info,
    fontSize: fontSize.md,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  evaluationStatusBadgeExcellent: {
    backgroundColor: colors.successSoft,
    color: colors.success,
  },
  evaluationStatusBadgeWarning: {
    backgroundColor: colors.warningSoft,
    color: colors.warning,
  },
  evaluationStatusBadgeDanger: {
    backgroundColor: colors.dangerSoft,
    color: colors.danger,
  },
  evaluationStatusBadgeScheduled: {
    backgroundColor: colors.secondarySoft,
    color: colors.info,
  },
  evaluationScoreText: {
    color: colors.text,
    fontSize: fontSize.xxl,
    fontWeight: '900',
    letterSpacing: 0,
    marginTop: spacing.md,
  },
  evaluationMessageList: {
    gap: spacing.xs,
    marginTop: spacing.sm,
  },
  evaluationMessageText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: 19,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: fontSize.xl,
    fontWeight: '900',
    letterSpacing: 0,
  },
  sectionSubtitle: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: 18,
    marginTop: spacing.xxs,
  },
  checkedCountText: {
    backgroundColor: colors.successSoft,
    borderRadius: radius.pill,
    color: colors.success,
    fontSize: fontSize.md,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  warningPanel: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warningBorder,
    borderRadius: radius.md,
    borderWidth: 1,
    marginTop: spacing.md,
    padding: spacing.md,
  },
  warningTitle: {
    color: colors.warning,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  warningBody: {
    color: colors.warning,
    fontSize: fontSize.md,
    lineHeight: 19,
    marginTop: spacing.xxs,
  },
  metricsStack: {
    gap: spacing.lg,
    marginTop: spacing.lg,
  },
  metricBlock: {
    gap: spacing.sm,
  },
  metricTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  metricName: {
    color: colors.text,
    fontSize: fontSize.base,
    fontWeight: '800',
  },
  metricValue: {
    color: colors.text,
    fontSize: fontSize.base,
    fontWeight: '900',
  },
  progressTrack: {
    backgroundColor: '#e7ece2',
    borderRadius: radius.sm,
    height: 9,
    overflow: 'hidden',
  },
  progressFill: {
    backgroundColor: colors.success,
    borderRadius: radius.sm,
    height: '100%',
  },
  metricMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  metricMetaText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
  },
  metricWarningText: {
    color: colors.warning,
    fontSize: fontSize.sm,
    fontWeight: '800',
  },
  searchPanel: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.card,
    borderWidth: 1,
    maxHeight: '86%',
    maxWidth: 640,
    padding: spacing.lg,
    width: '100%',
    ...cardShadow,
  },
  searchHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  searchInputRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  searchInput: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    borderWidth: 1,
    color: colors.text,
    flex: 1,
    fontSize: fontSize.base,
    minHeight: 46,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  searchMessageText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    marginTop: spacing.md,
  },
  searchErrorText: {
    color: colors.danger,
    fontSize: fontSize.md,
    fontWeight: '800',
    marginTop: spacing.md,
  },
  searchResultList: {
    gap: spacing.md,
    marginTop: spacing.md,
  },
  searchResultCard: {
    backgroundColor: colors.surfaceMuted,
    borderColor: '#e2eadf',
    borderRadius: radius.card,
    borderWidth: 1,
    padding: spacing.md,
  },
  searchResultHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  searchResultTitleBlock: {
    flex: 1,
    gap: spacing.xxs,
  },
  searchResultName: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: '900',
  },
  searchResultMeta: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 17,
  },
  resultWarning: {
    backgroundColor: colors.warningSoft,
    borderRadius: radius.pill,
    color: colors.warning,
    flexShrink: 1,
    fontSize: fontSize.sm,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
    textAlign: 'right',
  },
  searchNutritionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  searchNutritionItem: {
    backgroundColor: colors.surface,
    borderColor: '#e5ede1',
    borderRadius: radius.md,
    borderWidth: 1,
    flexGrow: 1,
    minWidth: 104,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  searchNutritionLabel: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    fontWeight: '800',
  },
  searchNutritionValue: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
    marginTop: spacing.xxs,
  },
  mealStack: {
    gap: spacing.md,
    marginTop: spacing.md,
  },
  mealSection: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.card,
    borderWidth: 1,
    padding: spacing.lg,
    ...cardShadow,
  },
  mealHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  mealTitle: {
    color: colors.text,
    fontSize: 19,
    fontWeight: '900',
    letterSpacing: 0,
  },
  mealStatus: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    marginTop: spacing.xxs,
  },
  mealWarning: {
    backgroundColor: colors.warningSoft,
    borderRadius: radius.pill,
    color: colors.warning,
    flexShrink: 1,
    fontSize: fontSize.sm,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
    textAlign: 'right',
  },
  mealSummaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  mealSummaryText: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.pill,
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  foodList: {
    borderTopColor: '#e6ede2',
    borderTopWidth: StyleSheet.hairlineWidth,
    marginTop: spacing.md,
  },
  foodRow: {
    alignItems: 'flex-start',
    borderBottomColor: '#e6ede2',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.md,
    paddingVertical: spacing.md,
  },
  foodRowLast: {
    borderBottomWidth: 0,
    paddingBottom: 0,
  },
  foodRowPressed: {
    opacity: 0.74,
  },
  emptyMealText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    paddingTop: spacing.md,
  },
  checkbox: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: '#8b9887',
    borderRadius: radius.sm,
    borderWidth: 2,
    height: 25,
    justifyContent: 'center',
    marginTop: spacing.xxs,
    width: 25,
  },
  checkboxChecked: {
    backgroundColor: colors.success,
    borderColor: colors.success,
  },
  checkboxMark: {
    color: colors.surface,
    fontSize: fontSize.base,
    fontWeight: '900',
    lineHeight: 17,
  },
  foodContent: {
    flex: 1,
    gap: spacing.xs,
  },
  foodHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  foodTitleBlock: {
    flex: 1,
    gap: spacing.xxs,
  },
  foodNameRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  foodName: {
    color: colors.text,
    flexShrink: 1,
    fontSize: fontSize.lg,
    fontWeight: '900',
  },
  foodGramsBadge: {
    backgroundColor: colors.primarySoft,
    borderRadius: radius.pill,
    color: colors.primary,
    fontSize: fontSize.sm,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  foodMeta: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 17,
  },
  foodNutritionLine: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  foodNutritionText: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.sm,
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '800',
    lineHeight: 17,
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  foodWarning: {
    color: colors.warning,
    fontSize: fontSize.sm,
    fontWeight: '800',
  },
  searchCloseButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: spacing.md,
  },
  searchCloseButtonPressed: {
    opacity: 0.72,
  },
  searchCloseButtonText: {
    color: colors.primary,
    fontSize: fontSize.sm,
    fontWeight: '900',
  },
  selectFoodButton: {
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    justifyContent: 'center',
    marginTop: spacing.md,
    minHeight: 38,
    minWidth: 72,
    paddingHorizontal: spacing.md,
  },
  selectFoodButtonPressed: {
    opacity: 0.72,
  },
  selectFoodButtonDisabled: {
    backgroundColor: '#d8ded5',
  },
  selectFoodButtonText: {
    color: colors.surface,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  selectFoodButtonDisabledText: {
    color: colors.textMuted,
  },
  mealTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  openSearchButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  openSearchButtonPressed: {
    opacity: 0.72,
  },
  openSearchButtonText: {
    color: colors.surface,
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 24,
  },
  gramsControl: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 0,
    flexWrap: 'wrap',
    gap: spacing.xs,
    justifyContent: 'flex-end',
  },
  gramsButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 32,
    minWidth: 44,
    paddingHorizontal: spacing.sm,
  },
  gramsButtonPressed: {
    opacity: 0.72,
  },
  gramsButtonText: {
    color: colors.primary,
    fontSize: fontSize.sm,
    fontWeight: '900',
  },
  removeFoodButton: {
    alignItems: 'center',
    backgroundColor: colors.dangerSoft,
    borderColor: colors.dangerBorder,
    borderRadius: radius.md,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 32,
    minWidth: 44,
    paddingHorizontal: spacing.sm,
  },
  removeFoodButtonText: {
    color: colors.danger,
    fontSize: fontSize.sm,
    fontWeight: '900',
  },
  modalOverlay: {
    alignItems: 'center',
    backgroundColor: colors.overlay,
    flex: 1,
    justifyContent: 'center',
    padding: spacing.lg,
  },
  modalScrim: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  portionModal: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.card,
    borderWidth: 1,
    maxWidth: 390,
    padding: spacing.lg,
    width: '100%',
    ...cardShadow,
  },
  portionModalTitle: {
    color: colors.text,
    fontSize: fontSize.xl,
    fontWeight: '900',
    letterSpacing: 0,
  },
  portionFoodName: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: '900',
    marginTop: spacing.sm,
  },
  portionServingText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 17,
    marginTop: spacing.xxs,
  },
  portionInputRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.lg,
  },
  portionInput: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    borderWidth: 1,
    color: colors.text,
    flex: 1,
    fontSize: 18,
    fontWeight: '900',
    minHeight: 48,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  portionUnitText: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: '900',
  },
  portionErrorText: {
    color: colors.danger,
    fontSize: fontSize.md,
    fontWeight: '800',
    marginTop: spacing.md,
  },
  portionPreview: {
    backgroundColor: colors.surfaceMuted,
    borderColor: '#e5ede1',
    borderRadius: radius.md,
    borderWidth: 1,
    gap: spacing.sm,
    marginTop: spacing.md,
    padding: spacing.md,
  },
  portionPreviewTitle: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  portionPreviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  portionPreviewItem: {
    flexGrow: 1,
    minWidth: 120,
  },
  portionPreviewLabel: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    fontWeight: '800',
  },
  portionPreviewValue: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
    marginTop: spacing.xxs,
  },
  portionButtonRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'flex-end',
    marginTop: spacing.lg,
  },
  portionCancelButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 72,
    paddingHorizontal: spacing.md,
  },
  portionCancelButtonText: {
    color: colors.primary,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  portionConfirmButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 72,
    paddingHorizontal: spacing.md,
  },
  portionConfirmButtonDisabled: {
    backgroundColor: '#d8ded5',
  },
  portionConfirmButtonText: {
    color: colors.surface,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  portionConfirmButtonDisabledText: {
    color: colors.textMuted,
  },
  portionButtonPressed: {
    opacity: 0.72,
  },
  goalPanel: {
    gap: spacing.md,
    marginTop: spacing.sm,
  },
  goalCard: {
    marginTop: spacing.md,
  },
  goalQuestionBlock: {
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  goalQuestionText: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: '900',
  },
  segmentedControl: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  segmentButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 78,
    paddingHorizontal: spacing.md,
  },
  segmentButtonActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  segmentButtonPressed: {
    opacity: 0.72,
  },
  segmentButtonText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  segmentButtonTextActive: {
    color: colors.primary,
  },
  goalFormGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
    marginTop: spacing.md,
  },
  goalInputGroup: {
    flexGrow: 1,
    minWidth: 136,
  },
  goalFieldLabel: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '900',
    marginBottom: spacing.xs,
  },
  goalInputRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  goalTextInput: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    borderWidth: 1,
    color: colors.text,
    flex: 1,
    fontSize: fontSize.base,
    minHeight: 44,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  goalUnitText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    fontWeight: '900',
    minWidth: 28,
  },
  goalChoiceSection: {
    gap: spacing.sm,
    marginTop: spacing.lg,
  },
  goalHelpText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 18,
  },
  activityList: {
    gap: spacing.sm,
  },
  activityOption: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  activityOptionActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  activityLabel: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  activityLabelActive: {
    color: colors.primary,
  },
  activityDescription: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 18,
    marginTop: spacing.xxs,
  },
  activityDescriptionActive: {
    color: colors.primary,
  },
  inBodySection: {
    gap: spacing.md,
    marginTop: spacing.md,
  },
  goalSubsectionTitle: {
    color: colors.text,
    fontSize: fontSize.base,
    fontWeight: '900',
  },
  goalResultSection: {
    gap: spacing.md,
    marginTop: spacing.md,
  },
  goalResultTitle: {
    color: colors.text,
    fontSize: fontSize.base,
    fontWeight: '900',
  },
  goalResultGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  goalResultItem: {
    backgroundColor: colors.surfaceMuted,
    borderColor: '#e2eadf',
    borderRadius: radius.card,
    borderWidth: 1,
    flexGrow: 1,
    minWidth: 126,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  goalResultLabel: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    fontWeight: '800',
  },
  goalResultValue: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
    marginTop: spacing.xxs,
  },
  goalDisclaimerText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 18,
  },
  goalWarningList: {
    gap: spacing.sm,
  },
  goalWarningText: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warningBorder,
    borderRadius: radius.md,
    borderWidth: 1,
    color: colors.warning,
    fontSize: fontSize.sm,
    fontWeight: '800',
    lineHeight: 18,
    padding: spacing.md,
  },
  goalErrorText: {
    backgroundColor: colors.dangerSoft,
    borderColor: colors.dangerBorder,
    borderRadius: radius.md,
    borderWidth: 1,
    color: colors.danger,
    fontSize: fontSize.sm,
    fontWeight: '800',
    lineHeight: 18,
    padding: spacing.md,
  },
  applyGoalButton: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: spacing.lg,
  },
  applyGoalButtonPressed: {
    opacity: 0.72,
  },
  applyGoalButtonText: {
    color: colors.surface,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  disclaimer: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: 20,
    marginTop: spacing.sm,
  },
  settingsStack: {
    gap: spacing.md,
    marginTop: spacing.md,
  },
  settingsActionSlot: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    gap: spacing.xs,
    marginTop: spacing.md,
    padding: spacing.md,
  },
  settingsActionTitle: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  settingsActionText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 18,
  },
  pinFoodButton: {
    alignItems: 'center',
    backgroundColor: colors.secondarySoft,
    borderColor: '#b9d4de',
    borderRadius: radius.md,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 32,
    minWidth: 44,
    paddingHorizontal: spacing.sm,
  },
  pinFoodButtonText: {
    color: colors.info,
    fontSize: fontSize.sm,
    fontWeight: '900',
  },
  pinFoodButtonPinned: {
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.borderStrong,
  },
  pinFoodButtonTextPinned: {
    color: colors.textMuted,
  },
  fixedMealBadge: {
    backgroundColor: colors.secondarySoft,
    borderRadius: radius.pill,
    color: colors.info,
    flexShrink: 1,
    fontSize: fontSize.sm,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  calendarMonthHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  calendarMonthTitle: {
    color: colors.text,
    flex: 1,
    fontSize: fontSize.xl,
    fontWeight: '900',
    letterSpacing: 0,
    textAlign: 'center',
  },
  calendarNavButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 44,
  },
  calendarNavButtonText: {
    color: colors.primary,
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 30,
  },
  calendarWeekHeader: {
    flexDirection: 'row',
    marginTop: spacing.lg,
  },
  calendarWeekdayCell: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 28,
    width: '14.285714%',
  },
  calendarWeekdayText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '900',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarDayCell: {
    alignItems: 'center',
    aspectRatio: 0.88,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    justifyContent: 'space-between',
    minHeight: 58,
    paddingHorizontal: spacing.xxs,
    paddingVertical: spacing.xs,
    width: '14.285714%',
  },
  calendarDayCellOutside: {
    backgroundColor: colors.surfaceMuted,
    opacity: 0.58,
  },
  calendarDayCellToday: {
    borderColor: colors.primary,
    borderWidth: 2,
  },
  calendarDayCellSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  calendarDayCellPressed: {
    opacity: 0.72,
  },
  calendarDayNumber: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  calendarDayNumberMuted: {
    color: colors.textSoft,
  },
  calendarDayNumberSelected: {
    color: colors.surface,
  },
  calendarStatusPill: {
    borderRadius: radius.pill,
    fontSize: 10,
    fontWeight: '900',
    lineHeight: 12,
    maxWidth: '100%',
    overflow: 'hidden',
    paddingHorizontal: spacing.xxs,
    paddingVertical: 2,
    textAlign: 'center',
  },
  calendarStatusPillGood: {
    backgroundColor: colors.successSoft,
    color: colors.success,
  },
  calendarStatusPillWarning: {
    backgroundColor: colors.warningSoft,
    color: colors.warning,
  },
  calendarStatusPillIncomplete: {
    backgroundColor: colors.dangerSoft,
    color: colors.danger,
  },
  calendarStatusPillScheduled: {
    backgroundColor: colors.secondarySoft,
    color: colors.info,
  },
  calendarStatusPillEmpty: {
    backgroundColor: colors.surfaceAlt,
    color: colors.textMuted,
  },
  calendarStatusPillSelected: {
    backgroundColor: colors.surface,
    color: colors.primary,
  },
  calendarSummaryCard: {
    marginTop: spacing.md,
  },
  calendarCheckedCountText: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.pill,
    color: colors.textMuted,
    fontSize: fontSize.md,
    fontWeight: '900',
    marginTop: spacing.md,
    overflow: 'hidden',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    alignSelf: 'flex-start',
  },
  calendarNutrientStack: {
    gap: spacing.md,
    marginTop: spacing.lg,
  },
  calendarMealLists: {
    gap: spacing.lg,
    marginTop: spacing.lg,
  },
  calendarMealListSection: {
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingTop: spacing.md,
  },
  calendarMealListTitle: {
    color: colors.text,
    fontSize: fontSize.base,
    fontWeight: '900',
  },
  calendarMealGroup: {
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  calendarMealGroupTitle: {
    color: colors.primary,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  calendarFoodSummaryRow: {
    alignItems: 'flex-start',
    backgroundColor: colors.surfaceMuted,
    borderColor: '#e2eadf',
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
    padding: spacing.md,
  },
  calendarFoodTitleBlock: {
    flex: 1,
    gap: spacing.xxs,
  },
  calendarFoodNameRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  calendarFoodName: {
    color: colors.text,
    flexShrink: 1,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  calendarFoodMeta: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 17,
  },
  calendarFoodKcalText: {
    color: colors.text,
    flexShrink: 0,
    fontSize: fontSize.md,
    fontWeight: '900',
    textAlign: 'right',
  },
  calendarEmptyText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: 19,
    marginTop: spacing.sm,
  },
  calendarSummaryAction: {
    marginTop: spacing.lg,
  },
  calendarEvaluationStatusBadgeEmpty: {
    backgroundColor: colors.surfaceAlt,
    color: colors.textMuted,
  },
  fixedMealTemplateList: {
    gap: spacing.md,
    marginTop: spacing.md,
  },
  fixedMealTemplateRow: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    padding: spacing.md,
  },
  fixedMealTemplateTitleRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  fixedMealTemplateTitleBlock: {
    flex: 1,
    gap: spacing.xxs,
  },
  fixedMealTemplateTitle: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  fixedMealTemplateMeta: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 17,
  },
  fixedMealTemplateBadge: {
    backgroundColor: colors.primarySoft,
    borderRadius: radius.pill,
    color: colors.primary,
    flexShrink: 1,
    fontSize: fontSize.sm,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  fixedMealTemplateItems: {
    gap: spacing.xs,
    marginTop: spacing.sm,
  },
  fixedMealTemplateItemText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 17,
  },
  fixedMealTemplateActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'flex-end',
    marginTop: spacing.md,
  },
  fixedMealTemplateActionButton: {
    minWidth: 72,
  },
  fixedMealTemplateDeleteButton: {
    backgroundColor: colors.dangerSoft,
    borderColor: colors.dangerBorder,
  },
  fixedMealTemplateDeleteButtonText: {
    color: colors.danger,
  },});
