import { StyleSheet } from 'react-native';

import { colors, fontSize, radius, shadow, spacing, typography } from './constants';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.background,
  },
  appContent: {
    flex: 1,
  },
  loadingScreen: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: spacing.xxl,
  },
  loadingTitle: {
    color: colors.text,
    fontSize: fontSize.xl,
    fontWeight: '900',
    letterSpacing: 0,
    textAlign: 'center',
  },
  loadingText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: 19,
    marginTop: spacing.xs,
    textAlign: 'center',
  },
  content: {
    alignSelf: 'center',
    maxWidth: 430,
    paddingBottom: 104,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xl,
    width: '100%',
  },
  tabBar: {
    backgroundColor: colors.surface,
    width: '100%',
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    minHeight: 84,
    paddingBottom: 10,
    paddingHorizontal: 0,
    paddingTop: spacing.xs,
  },
  tabButton: {
    alignItems: 'center',
    borderRadius: 0,
    flex: 1,
    gap: spacing.xxs,
    justifyContent: 'center',
    minHeight: 64,
    minWidth: 72,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
  },
  tabButtonActive: {
    backgroundColor: 'transparent',
  },
  tabButtonPressed: {
    opacity: 0.72,
  },
  tabIndicator: {
    backgroundColor: 'transparent',
    borderRadius: radius.pill,
    height: 3,
    width: 18,
  },
  tabIndicatorActive: {
    backgroundColor: colors.primary,
  },
  tabIconText: {
    color: colors.textMuted,
    fontSize: 19,
    fontWeight: '800',
    lineHeight: 22,
  },
  tabButtonText: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    fontWeight: '800',
    lineHeight: typography.lineHeight.xs,
    textAlign: 'center',
  },
  tabButtonTextActive: {
    color: colors.primary,
  },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.large,
    borderWidth: 1,
    padding: spacing.lg,
  },
  cardHero: {
    borderColor: '#d6e3d2',
    padding: spacing.xl,
    ...shadow.hero,
  },
  cardModal: {
    ...shadow.modal,
  },
  cardElevated: {
    ...shadow.hero,
  },
  cardMuted: {
    backgroundColor: colors.surfaceMuted,
  },
  sectionHeaderRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  sectionHeaderTextBlock: {
    flex: 1,
    gap: spacing.xxs,
  },
  sectionEyebrow: {
    color: colors.primary,
    fontSize: fontSize.xs,
    fontWeight: '900',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  sectionHeaderAction: {
    alignItems: 'flex-end',
    flexShrink: 0,
  },
  statusBadge: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: radius.pill,
    borderWidth: 1,
    flexDirection: 'row',
    flexShrink: 1,
    gap: spacing.xxs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  statusBadgeIcon: {
    fontSize: fontSize.xs,
    fontWeight: '900',
    lineHeight: typography.lineHeight.xs,
  },
  statusBadgeText: {
    fontSize: fontSize.sm,
    fontWeight: '900',
    lineHeight: typography.lineHeight.sm,
  },
  statusBadgeSuccess: {
    backgroundColor: colors.successSoft,
    borderColor: colors.successBorder,
  },
  statusBadgeWarning: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warningBorder,
  },
  statusBadgeDanger: {
    backgroundColor: colors.dangerSoft,
    borderColor: colors.dangerBorder,
  },
  statusBadgeScheduled: {
    backgroundColor: colors.scheduledSoft,
    borderColor: colors.scheduledBorder,
  },
  statusBadgeInfo: {
    backgroundColor: colors.infoSoft,
    borderColor: '#c4dbe4',
  },
  statusBadgeNeutral: {
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.borderStrong,
  },
  statusBadgeTextSuccess: {
    color: colors.success,
  },
  statusBadgeTextWarning: {
    color: colors.warning,
  },
  statusBadgeTextDanger: {
    color: colors.danger,
  },
  statusBadgeTextScheduled: {
    color: colors.scheduled,
  },
  statusBadgeTextInfo: {
    color: colors.info,
  },
  statusBadgeTextNeutral: {
    color: colors.textMuted,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.borderStrong,
    borderRadius: radius.medium,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.xxs,
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 40,
    paddingHorizontal: spacing.sm,
  },
  iconButtonSmall: {
    minHeight: 34,
    minWidth: 34,
    paddingHorizontal: spacing.xs,
  },
  iconButtonPrimary: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  iconButtonDanger: {
    backgroundColor: colors.dangerSoft,
    borderColor: colors.dangerBorder,
  },
  iconButtonSelected: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  iconButtonText: {
    color: colors.primary,
    fontSize: fontSize.md,
    fontWeight: '900',
    lineHeight: typography.lineHeight.md,
  },
  iconButtonTextPrimary: {
    color: colors.surface,
  },
  iconButtonTextDanger: {
    color: colors.danger,
  },
  iconButtonLabel: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '900',
    lineHeight: typography.lineHeight.sm,
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.large,
    borderWidth: 1,
    gap: spacing.xs,
    padding: spacing.lg,
  },
  emptyStateIcon: {
    color: colors.primary,
    fontSize: fontSize.xl,
    fontWeight: '900',
    lineHeight: typography.lineHeight.xl,
  },
  emptyStateTitle: {
    color: colors.text,
    fontSize: fontSize.base,
    fontWeight: '900',
    lineHeight: typography.lineHeight.base,
    textAlign: 'center',
  },
  emptyStateMessage: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: typography.lineHeight.md,
    textAlign: 'center',
  },
  emptyStateAction: {
    marginTop: spacing.xs,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.medium,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  primaryButtonText: {
    color: colors.surface,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.borderStrong,
    borderRadius: radius.medium,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  secondaryButtonText: {
    color: colors.primary,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  buttonPressed: {
    opacity: 0.72,
  },
  buttonDisabled: {
    backgroundColor: '#d8ded5',
    borderColor: '#d8ded5',
  },
  buttonDisabledText: {
    color: colors.textMuted,
  },
  selectButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderRadius: radius.medium,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 78,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  selectButtonWithDescription: {
    alignItems: 'flex-start',
    minHeight: 62,
    padding: spacing.md,
  },
  selectButtonActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  selectButtonText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  selectButtonTextActive: {
    color: colors.primary,
  },
  selectButtonDescription: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 17,
    marginTop: spacing.xxs,
  },
  selectButtonDescriptionActive: {
    color: colors.primary,
  },
  noticeBox: {
    backgroundColor: colors.infoSoft,
    borderColor: '#c9dde5',
    borderRadius: radius.medium,
    borderWidth: 1,
    marginTop: spacing.md,
    padding: spacing.md,
  },
  noticeBoxWarning: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warningBorder,
  },
  noticeBoxDanger: {
    backgroundColor: colors.dangerSoft,
    borderColor: colors.dangerBorder,
  },
  noticeTitle: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  noticeText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: 19,
    marginTop: spacing.xxs,
  },
  statRow: {
    alignItems: 'center',
    borderBottomColor: '#e8eee4',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
    paddingVertical: spacing.sm,
  },
  statRowLabel: {
    color: colors.textMuted,
    flex: 1,
    fontSize: fontSize.md,
    fontWeight: '700',
  },
  statRowValue: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
    textAlign: 'right',
  },
  header: {
    gap: spacing.xs,
    marginBottom: spacing.md,
  },
  eyebrow: {
    color: colors.primary,
    fontSize: fontSize.md,
    fontWeight: '800',
  },
  title: {
    color: colors.text,
    fontSize: fontSize.display,
    fontWeight: '900',
    letterSpacing: 0,
  },
  dateText: {
    color: colors.textMuted,
    fontSize: fontSize.base,
    lineHeight: 21,
  },
  todayTopStack: {
    gap: spacing.sm,
  },
  todayHeaderRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  todayHeaderTextBlock: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  dateCardHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  dateValueText: {
    color: colors.text,
    fontSize: fontSize.xxl,
    fontWeight: '900',
    letterSpacing: 0,
    marginTop: spacing.xxs,
  },
  dateBadge: {
    backgroundColor: colors.primarySoft,
    borderRadius: radius.pill,
    color: colors.primary,
    fontSize: fontSize.sm,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  dateControlRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.lg,
  },
  dateControlButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.borderStrong,
    borderRadius: radius.medium,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: spacing.md,
  },
  dateControlButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  dateControlButtonPressed: {
    opacity: 0.72,
  },
  dateControlButtonText: {
    color: colors.primary,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  dateControlButtonTextActive: {
    color: colors.surface,
  },
  summaryPanel: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.large,
    borderWidth: 1,
    marginTop: spacing.md,
    padding: spacing.lg,
  },
  summaryPanelHero: {
    gap: spacing.xl,
    width: '100%',
    marginTop: spacing.xs,
  },
  calorieHeroTopline: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  calorieHeroValueBlock: {
    gap: spacing.xs,
  },
  summaryKicker: {
    color: colors.textMuted,
    fontSize: fontSize.base,
    fontWeight: '700',
    lineHeight: typography.lineHeight.base,
  },
  calorieHeroValue: {
    color: colors.text,
    fontSize: 56,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 62,
  },
  calorieHeroMeta: {
    color: colors.textMuted,
    flex: 1,
    fontSize: fontSize.md,
    lineHeight: typography.lineHeight.md,
  },
  heroProgressTrack: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.pill,
    height: 6,
    overflow: 'hidden',
  },
  heroProgressFill: {
    backgroundColor: colors.primary,
    borderRadius: radius.pill,
    height: '100%',
  },
  calorieStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  calorieStatItem: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.medium,
    borderWidth: 1,
    flexGrow: 1,
    minWidth: 128,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  calorieStatLabel: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    fontWeight: '900',
    lineHeight: typography.lineHeight.xs,
  },
  calorieStatValue: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
    lineHeight: typography.lineHeight.md,
    marginTop: spacing.xxs,
  },
  summaryMacroList: {
    flexDirection: 'row',
    width: '100%',
    gap: spacing.sm,
  },
  summaryHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  evaluationPanel: {
    backgroundColor: colors.surface,
    borderColor: '#d5e4e8',
    borderRadius: radius.large,
    borderWidth: 1,
    marginTop: spacing.md,
    padding: spacing.lg,
  },
  evaluationHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  evaluationStatusBadge: {
    backgroundColor: colors.secondarySoft,
    borderRadius: radius.pill,
    color: colors.info,
    fontSize: fontSize.md,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  evaluationStatusBadgeExcellent: {
    backgroundColor: colors.successSoft,
    color: colors.success,
  },
  evaluationStatusBadgeWarning: {
    backgroundColor: colors.warningSoft,
    color: colors.warning,
  },
  evaluationStatusBadgeDanger: {
    backgroundColor: colors.dangerSoft,
    color: colors.danger,
  },
  evaluationStatusBadgeScheduled: {
    backgroundColor: colors.secondarySoft,
    color: colors.info,
  },
  evaluationScoreText: {
    color: colors.text,
    fontSize: fontSize.xxl,
    fontWeight: '900',
    letterSpacing: 0,
    marginTop: spacing.md,
  },
  evaluationMessageList: {
    gap: spacing.xs,
    marginTop: spacing.sm,
  },
  evaluationMessageText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: 19,
  },
  statusBanner: {
    alignItems: 'flex-start',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.large,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    padding: spacing.md,
  },
  statusBannerTextBlock: {
    flex: 1,
    gap: spacing.xs,
  },
  statusBannerTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  statusBannerTitle: {
    color: colors.text,
    fontSize: fontSize.base,
    fontWeight: '900',
    lineHeight: typography.lineHeight.base,
  },
  statusBannerScore: {
    color: colors.primary,
    fontSize: fontSize.base,
    fontWeight: '900',
    lineHeight: typography.lineHeight.base,
  },
  statusBannerMessage: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: typography.lineHeight.md,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: fontSize.xl,
    fontWeight: '900',
    letterSpacing: 0,
  },
  sectionSubtitle: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: 18,
    marginTop: spacing.xxs,
  },
  checkedCountText: {
    backgroundColor: colors.successSoft,
    borderRadius: radius.pill,
    color: colors.success,
    fontSize: fontSize.md,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  warningPanel: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warningBorder,
    borderRadius: radius.medium,
    borderWidth: 1,
    marginTop: spacing.md,
    padding: spacing.md,
  },
  warningTitle: {
    color: colors.warning,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  warningBody: {
    color: colors.warning,
    fontSize: fontSize.md,
    lineHeight: 19,
    marginTop: spacing.xxs,
  },
  metricsStack: {
    gap: spacing.lg,
    marginTop: spacing.lg,
  },
  metricBlock: {
    gap: spacing.sm,
  },
  metricTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  metricName: {
    color: colors.text,
    fontSize: fontSize.base,
    fontWeight: '800',
  },
  metricValue: {
    color: colors.text,
    fontSize: fontSize.base,
    fontWeight: '900',
  },
  progressTrack: {
    backgroundColor: '#e7ece2',
    borderRadius: radius.small,
    height: 9,
    overflow: 'hidden',
  },
  progressFill: {
    backgroundColor: colors.success,
    borderRadius: radius.small,
    height: '100%',
  },
  metricMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  metricMetaText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
  },
  metricWarningText: {
    color: colors.warning,
    fontSize: fontSize.sm,
    fontWeight: '800',
  },
  searchPanel: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.large,
    borderWidth: 1,
    maxHeight: '86%',
    maxWidth: 640,
    padding: spacing.lg,
    width: '100%',
    ...shadow.modal,
  },
  searchHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  searchInputRow: {
    marginTop: spacing.lg,
  },
  searchInput: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderRadius: radius.medium,
    borderWidth: 1,
    color: colors.text,
    flex: 1,
    fontSize: fontSize.base,
    minHeight: 46,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  searchMessageText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    marginTop: spacing.md,
  },
  searchErrorText: {
    color: colors.danger,
    fontSize: fontSize.md,
    fontWeight: '800',
    marginTop: spacing.md,
  },
  searchQueryDebugText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: typography.lineHeight.sm,
    marginTop: spacing.xs,
  },
  searchResultList: {
    gap: spacing.md,
    marginTop: spacing.md,
  },
  searchResultCard: {
    backgroundColor: colors.surfaceMuted,
    borderColor: '#e2eadf',
    borderRadius: radius.large,
    borderWidth: 1,
    padding: spacing.md,
  },
  searchResultHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  searchResultTitleBlock: {
    flex: 1,
    gap: spacing.xxs,
  },
  searchResultName: {
    color: colors.text,
    flexShrink: 1,
    fontSize: fontSize.lg,
    fontWeight: '900',
    lineHeight: typography.lineHeight.lg,
  },
  searchResultSourceName: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '700',
    lineHeight: typography.lineHeight.sm,
  },
  searchResultMeta: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 17,
  },
  resultWarning: {
    backgroundColor: colors.warningSoft,
    borderRadius: radius.pill,
    color: colors.warning,
    flexShrink: 1,
    fontSize: fontSize.sm,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
    textAlign: 'right',
  },
  searchNutritionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  searchNutritionItem: {
    backgroundColor: colors.surface,
    borderColor: '#e5ede1',
    borderRadius: radius.medium,
    borderWidth: 1,
    flexGrow: 1,
    minWidth: 104,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  searchNutritionLabel: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    fontWeight: '800',
  },
  searchNutritionValue: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
    marginTop: spacing.xxs,
  },
  mealStack: {
    backgroundColor: 'transparent',
    width: '100%',
    borderColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    marginTop: spacing.xl,
    overflow: 'visible',
  },
  mealSection: {
    borderTopColor: colors.divider,
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingBottom: spacing.lg,
    paddingTop: spacing.lg,
  },
  mealHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  mealTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 28,
  },
  mealStatus: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: typography.lineHeight.md,
    marginTop: spacing.xxs,
  },
  mealWarning: {
    backgroundColor: colors.warningSoft,
    borderRadius: radius.pill,
    color: colors.warning,
    flexShrink: 1,
    fontSize: fontSize.sm,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
    textAlign: 'right',
  },
  mealSummaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  mealSummaryText: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.pill,
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  foodList: {
    marginTop: spacing.md,
  },
  foodRow: {
    alignItems: 'flex-start',
    width: '100%',
    borderBottomColor: colors.divider,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    minHeight: 60,
    paddingVertical: 14,
  },
  foodRowLast: {
    borderBottomWidth: 0,
  },
  foodRowPressed: {
    opacity: 0.74,
  },
  emptyMealText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    paddingTop: spacing.md,
  },
  checkbox: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.borderStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 20,
    justifyContent: 'center',
    marginTop: 1,
    width: 20,
  },
  checkboxChecked: {
    backgroundColor: colors.success,
    borderColor: colors.success,
  },
  checkboxMark: {
    color: colors.surface,
    fontSize: fontSize.sm,
    fontWeight: '900',
    lineHeight: typography.lineHeight.sm,
  },
  foodContent: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  foodHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  foodTitleBlock: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  foodNameRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  foodName: {
    color: colors.text,
    flexShrink: 1,
    fontSize: fontSize.lg,
    fontWeight: '700',
    lineHeight: typography.lineHeight.lg,
  },
  foodSourceName: {
    color: colors.textSoft,
    fontSize: fontSize.xs,
    fontWeight: '700',
    lineHeight: typography.lineHeight.xs,
  },
  foodGramsBadge: {
    backgroundColor: colors.primarySoft,
    borderRadius: radius.pill,
    color: colors.primary,
    fontSize: fontSize.sm,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  foodMeta: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: typography.lineHeight.sm,
  },
  foodNutritionLine: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  foodNutritionText: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    fontWeight: '700',
    lineHeight: typography.lineHeight.xs,
  },
  foodWarning: {
    color: colors.warning,
    fontSize: fontSize.xs,
    fontWeight: '700',
    lineHeight: typography.lineHeight.xs,
  },
  searchCloseButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.borderStrong,
    borderRadius: radius.medium,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: spacing.md,
  },
  searchCloseButtonPressed: {
    opacity: 0.72,
  },
  searchCloseButtonText: {
    color: colors.primary,
    fontSize: fontSize.sm,
    fontWeight: '900',
  },
  selectFoodButton: {
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: colors.primary,
    borderRadius: radius.medium,
    justifyContent: 'center',
    marginTop: spacing.md,
    minHeight: 38,
    minWidth: 72,
    paddingHorizontal: spacing.md,
  },
  selectFoodButtonPressed: {
    opacity: 0.72,
  },
  selectFoodButtonDisabled: {
    backgroundColor: '#d8ded5',
  },
  selectFoodButtonText: {
    color: colors.surface,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  selectFoodButtonDisabledText: {
    color: colors.textMuted,
  },
  mealTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  openSearchButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.medium,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  openSearchButtonPressed: {
    opacity: 0.72,
  },
  openSearchButtonText: {
    color: colors.surface,
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 24,
  },
  gramsControl: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 0,
    flexWrap: 'wrap',
    gap: spacing.xs,
    justifyContent: 'flex-start',
    marginTop: 2,
  },
  gramsButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.medium,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    minWidth: 48,
    paddingHorizontal: spacing.sm,
  },
  gramsButtonPressed: {
    opacity: 0.72,
  },
  gramsButtonText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '800',
  },
  removeFoodButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.medium,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    minWidth: 48,
    paddingHorizontal: spacing.sm,
  },
  removeFoodButtonText: {
    color: colors.danger,
    fontSize: fontSize.sm,
    fontWeight: '800',
  },
  modalOverlay: {
    alignItems: 'center',
    backgroundColor: colors.overlay,
    flex: 1,
    justifyContent: 'center',
    padding: spacing.lg,
  },
  modalScrim: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  portionModal: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.large,
    borderWidth: 1,
    maxHeight: '86%',
    maxWidth: 430,
    padding: spacing.lg,
    width: '100%',
    ...shadow.modal,
  },
  portionModalTitle: {
    color: colors.text,
    fontSize: fontSize.xl,
    fontWeight: '900',
    letterSpacing: 0,
  },
  portionFoodName: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: '900',
    marginTop: spacing.sm,
  },
  portionSourceFoodName: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '700',
    lineHeight: typography.lineHeight.sm,
  },
  portionServingText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 17,
    marginTop: spacing.xxs,
  },
  portionInputRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.lg,
  },
  portionInput: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderRadius: radius.medium,
    borderWidth: 1,
    color: colors.text,
    flex: 1,
    fontSize: 18,
    fontWeight: '900',
    minHeight: 48,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  portionUnitText: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: '900',
  },
  portionErrorText: {
    color: colors.danger,
    fontSize: fontSize.md,
    fontWeight: '800',
    marginTop: spacing.md,
  },
  portionPreview: {
    backgroundColor: colors.surfaceMuted,
    borderColor: '#e5ede1',
    borderRadius: radius.medium,
    borderWidth: 1,
    gap: spacing.sm,
    marginTop: spacing.md,
    padding: spacing.md,
  },
  portionPreviewTitle: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  portionPreviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  portionPreviewItem: {
    flexGrow: 1,
    minWidth: 120,
  },
  portionPreviewLabel: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    fontWeight: '800',
  },
  portionPreviewValue: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
    marginTop: spacing.xxs,
  },
  portionButtonRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'flex-end',
    marginTop: spacing.lg,
  },
  portionCancelButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.borderStrong,
    borderRadius: radius.medium,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 72,
    paddingHorizontal: spacing.md,
  },
  portionCancelButtonText: {
    color: colors.primary,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  portionConfirmButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.medium,
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 72,
    paddingHorizontal: spacing.md,
  },
  portionConfirmButtonDisabled: {
    backgroundColor: '#d8ded5',
  },
  portionConfirmButtonText: {
    color: colors.surface,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  portionConfirmButtonDisabledText: {
    color: colors.textMuted,
  },
  portionButtonPressed: {
    opacity: 0.72,
  },
  goalPanel: {
    gap: spacing.md,
    marginTop: spacing.sm,
  },
  goalCard: {
    marginTop: spacing.md,
  },
  goalQuestionBlock: {
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  goalQuestionText: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: '900',
  },
  segmentedControl: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  segmentButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderRadius: radius.medium,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 78,
    paddingHorizontal: spacing.md,
  },
  segmentButtonActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  segmentButtonPressed: {
    opacity: 0.72,
  },
  segmentButtonText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  segmentButtonTextActive: {
    color: colors.primary,
  },
  goalFormGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
    marginTop: spacing.md,
  },
  goalInputGroup: {
    flexGrow: 1,
    minWidth: 136,
  },
  goalFieldLabel: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '900',
    marginBottom: spacing.xs,
  },
  goalInputRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  goalTextInput: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderRadius: radius.medium,
    borderWidth: 1,
    color: colors.text,
    flex: 1,
    fontSize: fontSize.base,
    minHeight: 44,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  goalUnitText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    fontWeight: '900',
    minWidth: 28,
  },
  goalChoiceSection: {
    gap: spacing.sm,
    marginTop: spacing.lg,
  },
  goalHelpText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 18,
  },
  activityList: {
    gap: spacing.sm,
  },
  activityOption: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderRadius: radius.medium,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  activityOptionActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  activityLabel: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  activityLabelActive: {
    color: colors.primary,
  },
  activityDescription: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 18,
    marginTop: spacing.xxs,
  },
  activityDescriptionActive: {
    color: colors.primary,
  },
  inBodySection: {
    gap: spacing.md,
    marginTop: spacing.md,
  },
  goalSubsectionTitle: {
    color: colors.text,
    fontSize: fontSize.base,
    fontWeight: '900',
  },
  goalResultSection: {
    gap: spacing.md,
    marginTop: spacing.md,
  },
  goalResultTitle: {
    color: colors.text,
    fontSize: fontSize.base,
    fontWeight: '900',
  },
  goalResultGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  goalResultItem: {
    backgroundColor: colors.surfaceMuted,
    borderColor: '#e2eadf',
    borderRadius: radius.large,
    borderWidth: 1,
    flexGrow: 1,
    minWidth: 126,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  goalResultLabel: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    fontWeight: '800',
  },
  goalResultValue: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
    marginTop: spacing.xxs,
  },
  goalDisclaimerText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 18,
  },
  goalWarningList: {
    gap: spacing.sm,
  },
  goalWarningText: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warningBorder,
    borderRadius: radius.medium,
    borderWidth: 1,
    color: colors.warning,
    fontSize: fontSize.sm,
    fontWeight: '800',
    lineHeight: 18,
    padding: spacing.md,
  },
  goalErrorText: {
    backgroundColor: colors.dangerSoft,
    borderColor: colors.dangerBorder,
    borderRadius: radius.medium,
    borderWidth: 1,
    color: colors.danger,
    fontSize: fontSize.sm,
    fontWeight: '800',
    lineHeight: 18,
    padding: spacing.md,
  },
  applyGoalButton: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: colors.primary,
    borderRadius: radius.medium,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: spacing.lg,
  },
  applyGoalButtonPressed: {
    opacity: 0.72,
  },
  applyGoalButtonText: {
    color: colors.surface,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  disclaimer: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: 20,
    marginTop: spacing.sm,
  },
  settingsStack: {
    gap: spacing.md,
    marginTop: spacing.xl,
  },
  settingsActionSlot: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.medium,
    borderWidth: 1,
    gap: spacing.xs,
    marginTop: spacing.md,
    padding: spacing.md,
  },
  settingsActionTitle: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  settingsActionText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 18,
  },
  pinFoodButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.medium,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    minWidth: 48,
    paddingHorizontal: spacing.sm,
  },
  pinFoodButtonText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '800',
  },
  pinFoodButtonPinned: {
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.borderStrong,
  },
  pinFoodButtonTextPinned: {
    color: colors.textMuted,
  },
  fixedMealBadge: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.small,
    color: colors.textMuted,
    flexShrink: 1,
    fontSize: fontSize.xs,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: spacing.xs,
    paddingVertical: 2,
  },
  calendarCard: {
    padding: spacing.md,
  },
  calendarMonthHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  calendarMonthTitleBlock: {
    alignItems: 'center',
    flex: 1,
    gap: spacing.xxs,
  },
  calendarMonthTitle: {
    color: colors.text,
    fontSize: fontSize.xl,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: typography.lineHeight.xl,
    textAlign: 'center',
  },
  calendarNavButton: {
    borderRadius: radius.pill,
    height: 42,
    minHeight: 42,
    minWidth: 42,
    paddingHorizontal: 0,
    width: 42,
  },
  calendarNavButtonText: {
    color: colors.primary,
    fontSize: 26,
    fontWeight: '900',
    lineHeight: 28,
  },
  calendarWeekHeader: {
    flexDirection: 'row',
    marginTop: spacing.lg,
  },
  calendarWeekdayCell: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 28,
    width: '14.285714%',
  },
  calendarWeekdayText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '900',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: spacing.xs,
  },
  calendarDayCell: {
    alignItems: 'center',
    aspectRatio: 0.92,
    borderColor: 'transparent',
    borderRadius: radius.medium,
    borderWidth: 1,
    justifyContent: 'space-between',
    minHeight: 58,
    paddingHorizontal: spacing.xxs,
    paddingVertical: spacing.xs,
    width: '14.285714%',
  },
  calendarDayCellOutside: {
    opacity: 0.45,
  },
  calendarDayCellToday: {
    borderColor: colors.primary,
    borderWidth: 1,
  },
  calendarDayCellSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  calendarDayCellPressed: {
    opacity: 0.72,
  },
  calendarDayNumber: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  calendarDayNumberMuted: {
    color: colors.textSoft,
  },
  calendarDayNumberSelected: {
    color: colors.surface,
  },
  calendarStatusRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xxs,
    justifyContent: 'center',
    maxWidth: '100%',
  },
  calendarStatusDot: {
    borderRadius: radius.pill,
    height: 6,
    width: 6,
  },
  calendarStatusDotGood: {
    backgroundColor: colors.success,
  },
  calendarStatusDotWarning: {
    backgroundColor: colors.warning,
  },
  calendarStatusDotIncomplete: {
    backgroundColor: colors.danger,
  },
  calendarStatusDotScheduled: {
    backgroundColor: colors.scheduled,
  },
  calendarStatusDotEmpty: {
    backgroundColor: colors.textSoft,
  },
  calendarStatusDotSelected: {
    backgroundColor: colors.surface,
  },
  calendarStatusText: {
    color: colors.textMuted,
    flexShrink: 1,
    fontSize: 10,
    fontWeight: '900',
    lineHeight: 12,
    textAlign: 'center',
  },
  calendarStatusTextSelected: {
    color: colors.surface,
  },
  calendarStatusPill: {
    borderRadius: radius.pill,
    fontSize: 10,
    fontWeight: '900',
    lineHeight: 12,
    maxWidth: '100%',
    overflow: 'hidden',
    paddingHorizontal: spacing.xxs,
    paddingVertical: 2,
    textAlign: 'center',
  },
  calendarStatusPillGood: {
    backgroundColor: colors.successSoft,
    color: colors.success,
  },
  calendarStatusPillWarning: {
    backgroundColor: colors.warningSoft,
    color: colors.warning,
  },
  calendarStatusPillIncomplete: {
    backgroundColor: colors.dangerSoft,
    color: colors.danger,
  },
  calendarStatusPillScheduled: {
    backgroundColor: colors.secondarySoft,
    color: colors.info,
  },
  calendarStatusPillEmpty: {
    backgroundColor: colors.surfaceAlt,
    color: colors.textMuted,
  },
  calendarStatusPillSelected: {
    backgroundColor: colors.surface,
    color: colors.primary,
  },
  calendarSummaryCard: {
    gap: spacing.lg,
    marginTop: spacing.md,
  },
  calendarSummaryTitleBlock: {
    flex: 1,
    gap: spacing.xxs,
  },
  calendarSummaryTopGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  calendarSummaryMetric: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.medium,
    borderWidth: 1,
    flexGrow: 1,
    minWidth: 132,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  calendarSummaryMetricLabel: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    fontWeight: '900',
    lineHeight: typography.lineHeight.xs,
  },
  calendarSummaryMetricValue: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: '900',
    lineHeight: typography.lineHeight.lg,
    marginTop: spacing.xxs,
  },
  calendarSummaryMetricMeta: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: typography.lineHeight.sm,
    marginTop: spacing.xxs,
  },
  calendarCountRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  calendarCountPill: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.pill,
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '900',
    lineHeight: typography.lineHeight.sm,
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  calendarCheckedCountText: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.pill,
    color: colors.textMuted,
    fontSize: fontSize.md,
    fontWeight: '900',
    marginTop: spacing.md,
    overflow: 'hidden',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    alignSelf: 'flex-start',
  },
  calendarNutrientStack: {
    gap: spacing.md,
    marginTop: spacing.lg,
  },
  calendarMealLists: {
    gap: spacing.lg,
    marginTop: spacing.lg,
  },
  calendarMealListSection: {
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingTop: spacing.md,
  },
  calendarMealListTitle: {
    color: colors.text,
    fontSize: fontSize.base,
    fontWeight: '900',
  },
  calendarMealGroup: {
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  calendarMealGroupTitle: {
    color: colors.primary,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  calendarFoodSummaryRow: {
    alignItems: 'flex-start',
    backgroundColor: colors.surfaceMuted,
    borderColor: '#e2eadf',
    borderRadius: radius.medium,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
    padding: spacing.md,
  },
  calendarFoodTitleBlock: {
    flex: 1,
    gap: spacing.xxs,
  },
  calendarFoodNameRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  calendarFoodName: {
    color: colors.text,
    flexShrink: 1,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  calendarFoodMeta: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 17,
  },
  calendarFoodKcalText: {
    color: colors.text,
    flexShrink: 0,
    fontSize: fontSize.md,
    fontWeight: '900',
    textAlign: 'right',
  },
  calendarEmptyText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: 19,
    marginTop: spacing.sm,
  },
  calendarSummaryAction: {
    marginTop: spacing.lg,
  },
  calendarEvaluationStatusBadgeEmpty: {
    backgroundColor: colors.surfaceAlt,
    color: colors.textMuted,
  },
  iconButtonLabelPrimary: {
    color: colors.surface,
  },
  iconButtonLabelDanger: {
    color: colors.danger,
  },
  progressFillCalories: {
    backgroundColor: colors.primary,
  },
  progressFillProtein: {
    backgroundColor: colors.success,
  },
  progressFillCarbohydrate: {
    backgroundColor: colors.secondary,
  },
  progressFillFat: {
    backgroundColor: colors.warning,
  },
  mealTitleBlock: {
    flex: 1,
    gap: spacing.xxs,
  },
  mealHeaderActions: {
    alignItems: 'flex-end',
    flexShrink: 0,
    gap: spacing.xs,
  },
  foodKcalText: {
    color: colors.textMuted,
    flexShrink: 0,
    fontSize: fontSize.base,
    fontWeight: '700',
    lineHeight: typography.lineHeight.base,
    textAlign: 'right',
  },
  calendarMonthSubtitle: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '700',
    lineHeight: typography.lineHeight.sm,
    textAlign: 'center',
  },
  fixedMealTemplateList: {
    gap: spacing.md,
    marginTop: spacing.md,
  },
  fixedMealTemplateRow: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.medium,
    borderWidth: 1,
    padding: spacing.md,
  },
  fixedMealTemplateTitleRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  fixedMealTemplateTitleBlock: {
    flex: 1,
    gap: spacing.xxs,
  },
  fixedMealTemplateTitle: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  fixedMealTemplateMeta: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 17,
  },
  fixedMealTemplateBadge: {
    backgroundColor: colors.primarySoft,
    borderRadius: radius.pill,
    color: colors.primary,
    flexShrink: 1,
    fontSize: fontSize.sm,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  fixedMealTemplateItems: {
    gap: spacing.xs,
    marginTop: spacing.sm,
  },
  fixedMealTemplateItemText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 17,
  },
  fixedMealTemplateActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'flex-end',
    marginTop: spacing.md,
  },
  fixedMealTemplateActionButton: {
    minWidth: 72,
  },
  fixedMealTemplateDeleteButton: {
    backgroundColor: colors.dangerSoft,
    borderColor: colors.dangerBorder,
  },
  fixedMealTemplateDeleteButtonText: {
    color: colors.danger,
  },
  goalSectionCard: {
    gap: spacing.lg,
  },
  goalResultCard: {
    gap: spacing.lg,
  },
  goalCalorieHero: {
    backgroundColor: colors.primarySoft,
    borderColor: '#c7dfd2',
    borderRadius: radius.large,
    borderWidth: 1,
    gap: spacing.xs,
    padding: spacing.lg,
  },
  goalCalorieLabel: {
    color: colors.primary,
    fontSize: fontSize.sm,
    fontWeight: '900',
    lineHeight: typography.lineHeight.sm,
  },
  goalCalorieValue: {
    color: colors.text,
    fontSize: 38,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 44,
  },
  goalCalorieMeta: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: typography.lineHeight.md,
  },
  goalMacroGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  goalMacroItem: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.medium,
    borderWidth: 1,
    flexGrow: 1,
    minWidth: 132,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  goalMacroLabel: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    fontWeight: '900',
    lineHeight: typography.lineHeight.xs,
  },
  goalMacroValue: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: '900',
    lineHeight: typography.lineHeight.lg,
    marginTop: spacing.xxs,
  },
  goalMacroMeta: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: typography.lineHeight.sm,
    marginTop: spacing.xxs,
  },
  goalMetabolismGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  goalMetricCard: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.medium,
    borderWidth: 1,
    flexGrow: 1,
    minWidth: 150,
    padding: spacing.md,
  },
  goalMetricLabel: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    fontWeight: '900',
    lineHeight: typography.lineHeight.xs,
  },
  goalMetricValue: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
    lineHeight: typography.lineHeight.md,
    marginTop: spacing.xxs,
  },
  goalMetricDescription: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: typography.lineHeight.sm,
    marginTop: spacing.xs,
  },
  settingsSectionCard: {
    gap: spacing.lg,
  },
  settingsList: {
    borderColor: colors.border,
    borderRadius: radius.medium,
    borderWidth: 1,
    overflow: 'hidden',
  },
  settingsRow: {
    alignItems: 'flex-start',
    backgroundColor: colors.surfaceMuted,
    borderBottomColor: colors.divider,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
    justifyContent: 'space-between',
    padding: spacing.md,
  },
  settingsRowTitleBlock: {
    flex: 1,
    gap: spacing.xxs,
    minWidth: 190,
  },
  settingsRowTitle: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
    lineHeight: typography.lineHeight.md,
  },
  settingsRowDescription: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: typography.lineHeight.sm,
  },
  settingsRowValue: {
    color: colors.primary,
    flexShrink: 1,
    fontSize: fontSize.md,
    fontWeight: '900',
    lineHeight: typography.lineHeight.md,
    textAlign: 'right',
  },
  settingsMutedText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: typography.lineHeight.sm,
    padding: spacing.md,
  },
  fixedMealSlotGroup: {
    borderColor: colors.border,
    borderRadius: radius.medium,
    borderWidth: 1,
    overflow: 'hidden',
  },
  fixedMealSlotHeader: {
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  fixedMealSlotTitle: {
    color: colors.text,
    fontSize: fontSize.base,
    fontWeight: '900',
    lineHeight: typography.lineHeight.base,
  },
  fixedMealSlotCount: {
    backgroundColor: colors.surface,
    borderRadius: radius.pill,
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '900',
    lineHeight: typography.lineHeight.sm,
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  fixedMealTemplateRowInactive: {
    backgroundColor: colors.surface,
  },
  fixedMealTemplateFoodList: {
    gap: spacing.xs,
    marginTop: spacing.md,
  },
  fixedMealTemplateFoodRow: {
    alignItems: 'flex-start',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.small,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  fixedMealTemplateFoodName: {
    color: colors.text,
    flex: 1,
    fontSize: fontSize.md,
    fontWeight: '900',
    lineHeight: typography.lineHeight.md,
    minWidth: 150,
  },
  fixedMealTemplateFoodMeta: {
    color: colors.textMuted,
    flexShrink: 1,
    fontSize: fontSize.sm,
    fontWeight: '800',
    lineHeight: typography.lineHeight.sm,
    textAlign: 'right',
  },
  fixedMealTemplateConfirmBox: {
    backgroundColor: colors.dangerSoft,
    borderColor: colors.dangerBorder,
    borderRadius: radius.medium,
    borderWidth: 1,
    gap: spacing.md,
    marginTop: spacing.md,
    padding: spacing.md,
  },
  fixedMealTemplateConfirmText: {
    color: colors.danger,
    fontSize: fontSize.sm,
    fontWeight: '800',
    lineHeight: typography.lineHeight.sm,
  },
  fixedMealTemplateConfirmActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'flex-end',
  },
  fixedMealTemplateConfirmDeleteButton: {
    backgroundColor: colors.danger,
    borderColor: colors.danger,
  },
  fixedMealTemplateConfirmDeleteButtonText: {
    color: colors.surface,
  },
  searchHeaderTextBlock: {
    flex: 1,
    gap: spacing.xxs,
    minWidth: 210,
  },
  searchInputBlock: {
    flex: 1,
    gap: spacing.xs,
  },
  searchInputLabel: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '900',
    lineHeight: typography.lineHeight.sm,
  },
  searchResultStatusRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  searchResultMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  searchResultMetaPill: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.pill,
    color: colors.textMuted,
    flexShrink: 1,
    fontSize: fontSize.sm,
    fontWeight: '800',
    lineHeight: typography.lineHeight.sm,
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  searchResultCalorieBlock: {
    alignItems: 'flex-end',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.medium,
    borderWidth: 1,
    flexGrow: 1,
    minWidth: 118,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  searchResultCalorieLabel: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    fontWeight: '900',
    lineHeight: typography.lineHeight.xs,
  },
  searchResultCalorieValue: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: '900',
    lineHeight: typography.lineHeight.lg,
    marginTop: spacing.xxs,
    textAlign: 'right',
  },
  portionHeader: {
    gap: spacing.xs,
  },
  portionInputBlock: {
    backgroundColor: colors.primarySoft,
    borderColor: '#c7dfd2',
    borderRadius: radius.large,
    borderWidth: 1,
    gap: spacing.xs,
    marginTop: spacing.lg,
    padding: spacing.md,
  },
  portionInputLabel: {
    color: colors.primary,
    fontSize: fontSize.sm,
    fontWeight: '900',
    lineHeight: typography.lineHeight.sm,
  },
  portionInputHelp: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: typography.lineHeight.sm,
  },
  portionPreviewHero: {
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: spacing.xxs,
    paddingBottom: spacing.md,
  },
  portionPreviewHeroLabel: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '900',
    lineHeight: typography.lineHeight.sm,
  },
  portionPreviewHeroValue: {
    color: colors.text,
    fontSize: fontSize.xxl,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: typography.lineHeight.xxl,
  },
  todayHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
    marginBottom: spacing.xl,
  },
  todayScreenTitle: {
    color: colors.text,
    fontSize: 28,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 34,
  },
  todayDateText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: typography.lineHeight.md,
    marginTop: 2,
  },
  todayDateNav: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 2,
    marginTop: spacing.xs,
  },
  dateNavButton: {
    alignItems: 'center',
    borderRadius: radius.medium,
    height: 36,
    justifyContent: 'center',
    width: 32,
  },
  dateNavTodayButton: {
    alignItems: 'center',
    borderRadius: radius.medium,
    justifyContent: 'center',
    minHeight: 36,
    minWidth: 42,
    paddingHorizontal: spacing.xs,
  },
  dateNavTodayButtonActive: {
    backgroundColor: colors.surfaceAlt,
  },
  dateNavButtonPressed: {
    opacity: 0.62,
  },
  dateNavButtonText: {
    color: colors.textMuted,
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 24,
  },
  dateNavTodayButtonText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '700',
    lineHeight: typography.lineHeight.sm,
  },
  dateNavTodayButtonTextActive: {
    color: colors.text,
  },
  calorieHeroMetricRow: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: spacing.xs,
  },
  calorieHeroUnit: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 31,
  },
  calorieHeroMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  calorieHeroProgressLabel: {
    color: colors.primary,
    flexShrink: 0,
    fontSize: fontSize.md,
    fontWeight: '700',
    lineHeight: typography.lineHeight.md,
    textAlign: 'right',
  },
  summaryMacroItem: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  summaryMacroLabel: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '700',
    lineHeight: typography.lineHeight.sm,
  },
  summaryMacroValue: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: '700',
    lineHeight: typography.lineHeight.lg,
  },
  summaryMacroProgressTrack: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.pill,
    height: 4,
    overflow: 'hidden',
  },
  summaryMacroProgressFill: {
    backgroundColor: colors.primary,
    borderRadius: radius.pill,
    height: '100%',
  },
  summaryMacroProgressFillMuted: {
    backgroundColor: colors.textSoft,
  },
  inlineStatus: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing.xs,
  },
  inlineStatusIcon: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    fontWeight: '900',
    lineHeight: typography.lineHeight.md,
    minWidth: 12,
    textAlign: 'center',
  },
  inlineStatusIconSuccess: {
    color: colors.success,
  },
  inlineStatusIconWarning: {
    color: colors.warning,
  },
  inlineStatusIconDanger: {
    color: colors.danger,
  },
  inlineStatusText: {
    color: colors.textMuted,
    flex: 1,
    fontSize: fontSize.sm,
    lineHeight: typography.lineHeight.sm,
  },
  mealKcalText: {
    color: colors.textMuted,
    flexShrink: 0,
    fontSize: fontSize.base,
    fontWeight: '700',
    lineHeight: typography.lineHeight.base,
    textAlign: 'right',
  },
  mealInlineWarning: {
    color: colors.warning,
    fontSize: fontSize.sm,
    lineHeight: typography.lineHeight.sm,
    marginTop: spacing.sm,
  },
  mealActionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: spacing.xs,
    justifyContent: 'space-between',
    marginTop: spacing.xs,
  },
  addFoodCompactButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    flexShrink: 0,
    gap: spacing.xs,
    minHeight: 44,
    paddingRight: spacing.xs,
  },
  addFoodCompactButtonPressed: {
    opacity: 0.62,
  },
  addFoodCompactIcon: {
    color: colors.primary,
    fontSize: fontSize.xl,
    fontWeight: '800',
    lineHeight: typography.lineHeight.xl,
  },
  addFoodCompactText: {
    color: colors.primary,
    fontSize: fontSize.base,
    fontWeight: '800',
    lineHeight: typography.lineHeight.base,
  },
  fixedMealManageButton: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: spacing.xxs,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: spacing.xs,
  },
  fixedMealManageIcon: {
    color: colors.primary,
    flexShrink: 0,
    fontSize: fontSize.md,
    fontWeight: '800',
    lineHeight: typography.lineHeight.md,
  },
  fixedMealManageButtonText: {
    color: colors.text,
    flexShrink: 1,
    fontSize: fontSize.base,
    fontWeight: '700',
    lineHeight: typography.lineHeight.base,
  },
  settingsGoalSection: {
    gap: spacing.md,
  },
  settingsGoalSectionTitle: {
    color: colors.text,
    fontSize: fontSize.xl,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: typography.lineHeight.xl,
  },
  settingsGoalEntry: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.large,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  settingsGoalEntryPressed: {
    opacity: 0.72,
  },
  settingsGoalRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
    minHeight: 38,
  },
  settingsGoalLabel: {
    color: colors.textMuted,
    flex: 1,
    fontSize: fontSize.md,
    lineHeight: typography.lineHeight.md,
  },
  settingsGoalValue: {
    color: colors.text,
    flexShrink: 0,
    fontSize: fontSize.md,
    fontWeight: '900',
    lineHeight: typography.lineHeight.md,
    textAlign: 'right',
  },
  settingsGoalDivider: {
    backgroundColor: colors.divider,
    height: StyleSheet.hairlineWidth,
  },
  settingsGoalActionText: {
    color: colors.text,
    flex: 1,
    fontSize: fontSize.md,
    fontWeight: '900',
    lineHeight: typography.lineHeight.md,
  },
  settingsGoalChevron: {
    color: colors.textSoft,
    fontSize: fontSize.xl,
    fontWeight: '800',
    lineHeight: typography.lineHeight.xl,
  },
  fixedMealManagerSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius.large,
    borderTopRightRadius: radius.large,
    marginTop: 'auto',
    maxHeight: '88%',
    overflow: 'hidden',
    width: '100%',
    ...shadow.modal,
  },
  fixedMealManagerHeader: {
    alignItems: 'flex-start',
    borderBottomColor: colors.divider,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
    paddingBottom: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
  },
  fixedMealManagerTitleBlock: {
    flex: 1,
    gap: spacing.xxs,
    minWidth: 0,
  },
  fixedMealManagerTitle: {
    color: colors.text,
    fontSize: fontSize.xl,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: typography.lineHeight.xl,
  },
  fixedMealManagerSubtitle: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: typography.lineHeight.sm,
  },
  fixedMealManagerCloseButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: spacing.xs,
  },
  fixedMealManagerCloseText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '700',
    lineHeight: typography.lineHeight.sm,
  },
  fixedMealManagerBody: {
    gap: spacing.md,
    paddingBottom: spacing.xl,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
  },
  fixedMealManagerScheduleRow: {
    borderBottomColor: colors.divider,
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: spacing.sm,
    paddingBottom: spacing.md,
  },
  fixedMealManagerScheduleRowInactive: {
    opacity: 0.58,
  },
  fixedMealManagerScheduleHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  fixedMealManagerScheduleTitleBlock: {
    flex: 1,
    gap: spacing.xxs,
    minWidth: 0,
  },
  fixedMealManagerFoodName: {
    color: colors.text,
    fontSize: fontSize.base,
    fontWeight: '800',
    lineHeight: typography.lineHeight.base,
  },
  fixedMealManagerFoodMeta: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: typography.lineHeight.sm,
  },
  fixedMealManagerScheduleMeta: {
    color: colors.textSoft,
    fontSize: fontSize.xs,
    fontWeight: '700',
    lineHeight: typography.lineHeight.xs,
  },
  fixedMealManagerActiveSwitch: {
    alignItems: 'center',
    borderColor: colors.borderStrong,
    borderRadius: radius.small,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 32,
    minWidth: 50,
    paddingHorizontal: spacing.sm,
  },
  fixedMealManagerActiveSwitchOn: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  fixedMealManagerActiveSwitchText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '800',
    lineHeight: typography.lineHeight.sm,
  },
  fixedMealManagerActiveSwitchTextOn: {
    color: colors.primary,
  },
  fixedMealPresetRow: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  fixedMealPresetButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: radius.small,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: spacing.xs,
  },
  fixedMealPresetButtonSelected: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  fixedMealPresetButtonText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '700',
    lineHeight: typography.lineHeight.sm,
  },
  fixedMealPresetButtonTextSelected: {
    color: colors.primary,
    fontWeight: '800',
  },
  fixedMealWeekdayRow: {
    flexDirection: 'row',
    gap: spacing.xs,
    justifyContent: 'space-between',
  },
  fixedMealWeekdayChip: {
    alignItems: 'center',
    borderColor: colors.borderStrong,
    borderRadius: radius.small,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 36,
    minWidth: 0,
  },
  fixedMealWeekdayChipSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  fixedMealWeekdayChipDisabled: {
    opacity: 0.72,
  },
  fixedMealWeekdayChipText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '800',
    lineHeight: typography.lineHeight.sm,
  },
  fixedMealWeekdayChipTextSelected: {
    color: colors.surface,
  },
  fixedMealManagerDeleteRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  fixedMealManagerDeleteButton: {
    minHeight: 36,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  fixedMealManagerDeleteButtonText: {
    color: colors.danger,
    fontSize: fontSize.sm,
  },
  fixedMealManagerConfirmBox: {
    backgroundColor: colors.dangerSoft,
    borderColor: colors.dangerBorder,
    borderRadius: radius.medium,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  fixedMealManagerConfirmText: {
    color: colors.danger,
    fontSize: fontSize.sm,
    lineHeight: typography.lineHeight.sm,
  },
  fixedMealManagerConfirmActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'flex-end',
  },
  fixedMealManagerConfirmButton: {
    minHeight: 36,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  fixedMealManagerConfirmDeleteButton: {
    backgroundColor: colors.danger,
    borderColor: colors.danger,
  },
  fixedMealManagerConfirmDeleteButtonText: {
    color: colors.surface,
  },
  fixedMealManagerEmptyState: {
    gap: spacing.xs,
    paddingVertical: spacing.md,
  },
  fixedMealManagerEmptyTitle: {
    color: colors.text,
    fontSize: fontSize.base,
    fontWeight: '700',
    lineHeight: typography.lineHeight.base,
  },
  fixedMealManagerEmptyText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: typography.lineHeight.sm,
  },
  fixedMealManagerAddButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
    minHeight: 44,
  },
  fixedMealManagerAddIcon: {
    color: colors.primary,
    fontSize: fontSize.xl,
    fontWeight: '800',
    lineHeight: typography.lineHeight.xl,
  },
  fixedMealManagerAddText: {
    color: colors.primary,
    fontSize: fontSize.md,
    fontWeight: '800',
    lineHeight: typography.lineHeight.md,
  },
  fixedMealWeekdayEditor: {
    gap: spacing.sm,
  },
  fixedMealWeekdayEditorLabel: {
    color: colors.text,
    fontSize: fontSize.sm,
    fontWeight: '800',
    lineHeight: typography.lineHeight.sm,
  },
  fixedMealManagerActionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  fixedMealManagerEditBlock: {
    gap: spacing.sm,
  },
  fixedMealManagerEditActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'flex-end',
  },
  fixedMealManagerEditButton: {
    minHeight: 36,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  fixedMealScheduleSetupModal: {
    alignSelf: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.large,
    borderWidth: 1,
    maxHeight: '86%',
    maxWidth: 430,
    overflow: 'hidden',
    padding: spacing.lg,
    width: '90%',
    ...shadow.modal,
  },
  fixedMealScheduleSetupHeader: {
    gap: spacing.xxs,
    marginBottom: spacing.md,
  },
  fixedMealScheduleSetupTitle: {
    color: colors.text,
    fontSize: fontSize.xl,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: typography.lineHeight.xl,
  },
  fixedMealScheduleSetupFoodName: {
    color: colors.text,
    fontSize: fontSize.base,
    fontWeight: '800',
    lineHeight: typography.lineHeight.base,
  },
  fixedMealScheduleSetupMeta: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: typography.lineHeight.sm,
  },
  fixedMealScheduleSetupActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'space-between',
    marginTop: spacing.lg,
  },
  fixedMealScheduleSetupButton: {
    flex: 1,
    minHeight: 40,
  },
});
